tasks:
  - name: docker
    command: |
      docker-compose up
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
      AWS_ACCESS_KEY_ID: myaccesskey
      AWS_SECRET_ACCESS_KEY: mysecretkey
      AWS_DEFAULT_REGION: us-east-1
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode